### ISSUE TITLE
Property 'rbp' does not exist on type 'CpuContext'.

### ISSUE THREAD

**Issue by qsirwyk** [oleavr/frida-agent-example#36]
LogRed('context:',JSON.stringify(t.context));
  LogRed('arch:',Process.arch);
  //let rbp = new NativePointer(t.context.rbp);

context: {"pc":"0x10c8aaafc","sp":"0x7ff7b36c78e8","rax":"0x7fb9520eb120","rcx":"0x7ff801d8c8d3","rdx":"0x25ff","rbx":"0x7fb9520eb120","rsp":"0x7ff7b36c78e8","rbp":"0x7ff7b36c7920","rsi":"0x7ff81c83f5aa","rdi":"0x7fb9520eb120","r8":"0x7fb94fef15b0","r9":"0x7ff7b36c7a58","r10":"0x7fb94f8b17d2","r11":"0x10c8aaafc","r12":"0x1c00","r13":"0x7ff801d87200","r14":"0x7fb9520eb120","r15":"0x0","rip":"0x10c8aaafc"}
arch: x64

---
 
 LogRed('context:',JSON.stringify(t.context));
  LogRed('arch:',Process.arch);
 let rbp = new NativePointer(t.context.rbp);
 
 
 (base)   npm run build

> frida-agent-example@1.0.0 build
> frida-compile agent/proxifier.ts -o agent/_agent.js -c

/Users/qsir/work/frida/ios/frida-agent/agent/proxifier.ts (26,51): Property 'rbp' does not exist on type 'CpuContext'.
  Property 'rbp' does not exist on type 'PortableCpuContext'.
Error: compilation failed
    at Module.build (file:///Users/qsir/work/frida/ios/frida-agent/node_modules/frida-compile/dist/compiler.js:34:15)
    at main (file:///Users/qsir/work/frida/ios/frida-agent/node_modules/frida-compile/dist/cli.js:37:33)
    at file:///Users/qsir/work/frida/ios/frida-agent/node_modules/frida-compile/dist/cli.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

It seems that frida-gum fails to properly identify what the current architecture is.

**Comment by oleavr** [comment]
You need to cast the context to the appropriate type depending on `Process.arch`.
